# computação Quantica
## Aula 3

### Números Complexos com numpy

In [2]:
import numpy as np

In [3]:
# z = u + iv
z = 3 + 1j*5
print(z)

(3+5j)


In [4]:
w = 4 + 2*1j
print(w)

(4+2j)


In [5]:
# operações fundamentais de números complexos
print(z+w)
print(z*w)
print(z-w)
print(z/w)

(7+7j)
(2+26j)
(-1+3j)
(1.1+0.7j)


In [6]:
# conjugado de complexo
np.conjugate(z)

(3-5j)

In [7]:
# recebendo a parte real 
print(z.real)
# recebendo a parte imaginaria 
print(w.imag)

3.0
2.0


In [8]:
# encontrando o módulo do complexo
print(abs(z))
a = 1 + 1*1j
print(a)
print(abs(a))
print(np.sqrt(2))

5.830951894845301
(1+1j)
1.4142135623730951
1.4142135623730951


### Forma de Euler

$$
e^{i\theta} = \cos(\theta) + i \cdot \sin(\theta)
$$
#### Números complexos na forma de Euler
pela representação vetorial dos números complexos em um plano 
dos imaginários pelos reais, podemos definir a forma polar dos 
números complexos. <br><br>
partindo de 
$$
z = a + ib
$$
temos que: $$\cos(\theta) = \frac{a}{|z|}$$ e $$\sin(\theta) = \frac{b}{|z|}$$
logo
$$z  = a + ib = |z|\cos(\theta) + i|z|\sin(\theta) $$
$$ = |z|[\cos(\theta)+i\sin(\theta)]$$
$$ = |z|e^{i\theta}$$

### Vetores complexos

$|\psi>$ $\rightarrow$ Ket  (vetor coluna complexo) <br>
$<\psi|$ $\rightarrow$ Bra (vetor linha complexo)<br>
$<\psi|\psi>$ $\rightarrow$ Braket (produto interno)

Os elementos do espaço $\mathbb{C}^R$ são todos os vetores do tipo: <br>
$$|\psi>\ = (z_1, z_2, \dots , z_n)$$
onde $$z_1, z_2, \dots ,zn \in \mathbb{C}$$

ou seja cada $|\psi>$ pode ser representado por um vetor coluna: 
$$|\psi>\ = \left(\begin{array}{cc}
z_1\\
z_2\\
\vdots\\
z_n
\end{array}\right)$$

### Operação de transposição conjugada

Realiza a matriz transposta e faz o conjugado de todos os números complexos da matriz
$$
\mathbf{A}=\left(\begin{array}{cc}
z_{11} & z_{12}\\
 z_{21} & z_{22}
\end{array}\right) \rightarrow
\mathbf{A^+}=\left(\begin{array}{cc}
z_{11}^* & z_{21}^*\\
z_{12}^* & z_{22}^*
\end{array}\right)
$$
lembrar do simbolo de +

Aplicando a operação de transposição conjugada no vetor ket
$$
|\psi>\ = \left(\begin{array}{cc}
z_1\\
z_2\\
\vdots\\
z_n
\end{array}\right) 
\rightarrow
|\psi>^+ = \left(\begin{array}{cc}
z_1^* &
z_2^* &
\dots &
z_n^*
\end{array}\right)
$$


e temos
$$
|\psi>^+ =\ <\psi|
$$
"Ket com operação de transposição conjugada é igual a Bra"

### Produto Interno 

Definindo: <br>
$|\psi>\ = \left(\begin{array}{cc}
z_1\\
z_2\\
\vdots\\
z_n
\end{array}\right)
\qquad e\qquad 
|\phi>\ = \left(\begin{array}{cc}
w_1\\
w_2\\
\vdots\\
w_n
\end{array}\right)$

Temos o produto interno entre $|\psi>$ e $|\phi>$ sendo
$$<\psi|\phi>\ = \left(\begin{array}{cc}
z_1^* & z_2^* & \dots & z_n^*
\end{array}\right) . \left(\begin{array}{cc}
w_1\\
w_2\\
\vdots\\
w_n
\end{array}\right) = z_1^*w_1 + z_2^*w_2 + \dots + z_n^*w_n
$$
como temos uma matriz linha multiplicada por uma matriz coluna temos como resultado um escalar

temos também que 
$$<\psi|\phi>\ = (|\psi>^+, |\phi>) $$
e que o produto interno é um BraKet

### Produtol Externo

o produto externo é um KetBra
$$
|\psi><\phi|\ = 
\left(\begin{array}{cc}
z_1\\
z_2\\
\vdots\\
z_n
\end{array}\right) 
. 
\left(\begin{array}{cc}
w_1^* & w_2^* & \dots & w_n^*
\end{array}\right) = \left(\begin{array}{cc}
z_1w_1^* & z_1w_2^* & \dots & z_1w_n^*\\ 
z_2w_1^* & z_2w_2^* & \dots & z_2w_n^*\\ 
\vdots & \vdots & \ddots & \vdots \\
z_nw_1^* & z_nw_2^* & \dots & z_nw_n^*\\ 
\end{array}\right)
$$
como é uma multiplicação de matriz coluna por matriz linha temos uma matriz nxn

### Produto Interno e Externo no numpy

In [9]:
vket = np.array([[1/np.sqrt(2)],[1j/np.sqrt(2)]])   # vetor V na forma Ket (vetor coluna)
print(vket)

[[0.70710678+0.j        ]
 [0.        +0.70710678j]]


In [10]:
vbra = np.transpose(np.conjugate(vket))   # para obter o vetor V na forma Bra temos que fazer a operação de transposição conjugada
# ou seja fazer o conjugado de todos os valores de V e depois fazer sua matriz conjugada
print(vbra)

[[0.70710678-0.j         0.        -0.70710678j]]


In [11]:
# Produto interno (BraKet)
print(vbra@vket)

[[1.+0.j]]


In [12]:
# Produto externo (KetBra)
print(vket@vbra)

[[0.5+0.j  0. -0.5j]
 [0. +0.5j 0.5+0.j ]]


### Produto Tensorial

#### Dimensão do resultado
$$
\begin{align*}
E_1 \otimes E_2 &= E \\
dim(E_1) . dim(E_2) &= dim(E)
\end{align*}
$$

#### Operação do produto tensorial
$$
|\psi>\otimes\ |\phi>
\ = 
\left(\begin{array}{cc}
z_1\\
z_2\\
\vdots\\
z_n
\end{array}\right)
\otimes
\left(\begin{array}{cc}
w_1\\
w_2\\
\vdots\\
w_n
\end{array}\right)
\ = 
\left(\begin{array}{cc}
z_1.\left(\begin{array}{cc}
w_1\\
w_2\\
\vdots\\
w_n
\end{array}\right) \\
z_2.\left(\begin{array}{cc}
w_1\\
w_2\\
\vdots\\
w_n
\end{array}\right) \\
\vdots\\
z_n.\left(\begin{array}{cc}
w_1\\
w_2\\
\vdots\\
w_n
\end{array}\right)
\end{array}\right)
\ = 
\left(\begin{array}{cc}
z_1w_1\\
z_1w_2\\
z_1w_3\\
\vdots\\
z_1w_n\\
z_2w_1\\
z_2w_2\\
z_2w_3\\
\vdots\\
z_2w_n\\
\vdots\\
z_nw_n
\end{array}\right)
$$

o convencional é enfiar a operação no sentido da direita para esquerda

### Produto tensorial no numpy

In [19]:
# definindo as bases computacionais em Ket e Bra
v0 = np.array([[1],[0]])
v1 = np.array([[0],[1]])
v0l = np.conjugate(v0).T 
v1l = np.conjugate(v1).T 

In [21]:
psi = (1/np.sqrt(2))*(v0 + v1)
print(psi)

[[0.70710678]
 [0.70710678]]


In [22]:
# fazendo o produto tensorial de psi com v0
np.kron(psi,v0)

array([[0.70710678],
       [0.        ],
       [0.70710678],
       [0.        ]])

### Lista de Exercícios 2

#### 1

In [16]:
z = 2 + 1j*3
w = 5 - 1j*2
print(z)
print(w)
print(z+w)
print(z*w)
print(np.conjugate(z))
print(np.conjugate(w))
print(w/z)
print(abs(z))
print(abs(w))
# C

(2+3j)
(5-2j)
(7+1j)
(16+11j)
(2-3j)
(5+2j)
(0.30769230769230765-1.4615384615384617j)
0.3076923076923077
3.605551275463989
5.385164807134504


#### 5 ****

In [46]:
M = np.array([[1,1],[1,-1]])
Had = (1/np.sqrt(2))*M 
print(Had)  

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


#### 6

In [28]:
psi = (1/np.sqrt(2))*(v0-1j*v1) # ket
psil = np.conjugate(psi).T      # bra 
print(psi@psil)

[[0.5+0.j  0. +0.5j]
 [0. -0.5j 0.5+0.j ]]


In [29]:
psi = (1/2)*(np.kron(v0,v0)+np.kron(v0,v1)+np.kron(v1,v0)+np.kron(v1,v1))
psil = np.conjugate(psi).T 
print(psi@psil)
# B

[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]


#### 7

In [30]:
psi = (np.sqrt(3)/2)*(v0+v1)
psil = np.conjugate(psi).T 
print((v0l@psi)*(psil@v0))
# C

[[0.75]]


#### 8

In [31]:
psi = (1/np.sqrt(2))*(v0 + v1)
psil = np.conjugate(psi).T 
print(psi@psil)
print(((1/2)*(v0@v0l))+((1/2)*(v1@v1l)))
# E

[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0. ]
 [0.  0.5]]


#### 9

In [32]:
M = (1/2)*(v0@v0l) + (1/2)*(v1@v1l)
print(v0l@M@v0)
print(v0l@M@v1)
print(v1l@M@v0)
print(v1l@M@v1)
# A

[[0.5]]
[[0.]]
[[0.]]
[[0.5]]


#### 10

In [43]:
psi = np.array([[np.sqrt(2)/2],[(np.sqrt(2)/2)*1j]])
psil = np.transpose(np.conjugate(psi))
print(psi@psil)
# E

[[0.5+0.j  0. -0.5j]
 [0. +0.5j 0.5+0.j ]]
