# Computação Quântica
## Aula 2

### Matrizes

In [3]:
# Testes de matrizes
M = [[0,1],[3,4]]
for i in M:
    print(i)
print("# andando linha por linha")
for i in range(len(M)):
    for j in range(len(M[0])):
        print(M[i][j], end=' ')
    print()
print("fim da matriz")
print("# andando coluna por coluna")
for i in range(len(M)):
    for j in range(len(M[0])):
        print(M[j][i], end=" ")
    print()
print("fim da matriz")

[0, 1]
[3, 4]
# andando linha por linha
0 1 
3 4 
fim da matriz
# andando coluna por coluna
0 3 
1 4 
fim da matriz


#### Definição de matrizes com a biblioteca numpy

In [4]:
import numpy as np
Sz = np.array([[1,0],[0,-1]]) # sigma z umas das matrizes de Pauli
print(Sz)

[[ 1  0]
 [ 0 -1]]


#### Soma de matriz, Multiplicação e divisão por escalar

In [5]:
v0 = np.array([[1],[0]])   # representação de um qubits? (ainda não entendi direito essa parte)
v1 = np.array([[0],[1]])
Psi = 2*v0 + 3*v1          # o Psi é uma combinação linear do estados v0 e v1  
print(Psi)

[[2]
 [3]]


também a definição de raiz no numpy

In [6]:
M = np.array([[1,1],[1,-1]])
Had = (1/np.sqrt(2))*M   # matriz M divida por raiz de 2
print(Had)               # Hadamard é uma das portas lógicas da computação quântica (entender melhor) 

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


#### Multiplicação de matriz

In [7]:
print(Sz@Sz)

[[1 0]
 [0 1]]


In [8]:
print(Had@Had) # Hadamard ao quadrado é a matriz identidade

[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]


In [9]:
print(Had@v0) # Hadamard aplicada a um estado 

[[0.70710678]
 [0.70710678]]


#### Matriz transposta

In [10]:
v0l = np.transpose(v0)   # faz a transposta da matriz (transforma linha em coluna)
print(v0l)

[[1 0]]


In [11]:
print(v0l@v0)    # linha x coluna resulta em um escalar  (representação <0|0>)
print(v0@v0l)    # coluna x linha resulta em uma matriz  (representação |0><0|)

[[1]]
[[1 0]
 [0 0]]


### Combinação linear
representando o estado Psi em diversas bases com combinações lineares diferentes

#### representando Psi como uma combinação linear dos estados |0> e |1>

In [12]:
Psi = (1/np.sqrt(2))*v0 + (1/np.sqrt(2))*v1
print(Psi)

[[0.70710678]
 [0.70710678]]


#### representando Psi como uma combinação linear dos estados |+> e |->

In [13]:
vp = np.array([[1/np.sqrt(2)],[1/np.sqrt(2)]])   # vp = "v plus" estado |+>
vm = np.array([[1/np.sqrt(2)],[-1/np.sqrt(2)]])  # vm = "v minus" estado |->
Psi2 = 1*vp + 0*vm
print(Psi2)

[[0.70710678]
 [0.70710678]]


qualquer estado de qubit pode ser representado por combinação linear da base computacional |0> e |1> ou da base |+> e |->

### Lista de exercícios 1

#### 1. 

a<sub>ij</sub> = 3i-j
qual o elemento a<sub>22</sub>? <br>
a<sub>22</sub> = 3.2 - 2 = 4 <br>
'#' a

#### 2.

In [14]:
A = np.array([[1,2,1],[2,3,1],[0,4,1]])
B = np.array([[3,6,1],[4,1,2],[5,2,1]])
C = A@B
print(C)
# d

[[16 10  6]
 [23 17  9]
 [21  6  9]]


#### 3.

In [15]:
A = np.array([[1,2],[3,-4]])
B = np.array([[5,0],[-6,7]])
C = np.array([[1,-3,4],[2,6,-5]])
print(5*A - 2*B)
print(2*A + 3*B)
# b

[[ -5  10]
 [ 27 -34]]
[[ 17   4]
 [-12  13]]


#### 4.

In [16]:
print(A@B)
print((A@B)@C)
# c

[[ -7  14]
 [ 39 -28]]
[[  21  105  -98]
 [ -17 -285  296]]


#### 5.

In [17]:
print(B@C)
print(A@(B@C))
# e

[[  5 -15  20]
 [  8  60 -59]]
[[  21  105  -98]
 [ -17 -285  296]]


#### 6.

In [18]:
print((A@B)@C - A@(B@C))
# d

[[0 0 0]
 [0 0 0]]


#### 7.

In [19]:
print(A@A)
print(A@C)
# d

[[ 7 -6]
 [-9 22]]
[[  5   9  -6]
 [ -5 -33  32]]


#### 8.

In [20]:
At = (np.transpose(A))
Bt = (np.transpose(B))
print(At)
print(Bt)
print(At@Bt)
# e

[[ 1  3]
 [ 2 -4]]
[[ 5 -6]
 [ 0  7]]
[[  5  15]
 [ 10 -40]]


#### 9.

In [21]:
print((At@Bt)-np.transpose(A@B))
# e

[[ 12 -24]
 [ -4 -12]]
