In [1]:
# No python a função 'print()' imprime o que estiver dentro dos parenteses '()' na tela

In [2]:
# exemplo, para imprimir 'eu amo física!'

In [3]:
print('eu amo física!')

eu amo física!


In [4]:
# O python instalado já vem com várias capacidades, como imprimir.

In [5]:
# Porém, para fazer operações especializadas, é necessário instalar outros 'pacotes'.

In [6]:
# Um desses pacotes permite fazer operações matemáticas avançadas, e se chama 'numpy'.

In [7]:
# Para usarmos o pacote 'numpy', precisamos importá-lo.

In [8]:
import numpy as np

In [9]:
# Para usar as funções do pacote, usamos a abreviação que definimos 'np', seguida de um ponto.

In [10]:
# Após esse ponto, especificamos a função que queremos usar: 'np.funçãoQueQueroUsar()'

In [11]:
# A função 'array()', por exemplo, cria uma matriz a partir do que estiver dentro dos parenteses.

In [12]:
# A função 'sqrt()' nos devolve a raiz quadrada do que estiver dentro dos parenteses.

In [13]:
# Vamos usar o numpy para criar uma matriz quadrada (2 linhas x 2 colunas) 

# e a salvar na variável 'Sz'

In [14]:
Sz = np.array([[1,0], [0, -1]])

In [15]:
# imprimindo a matriz 'Sz'

In [16]:
print(Sz)

[[ 1  0]
 [ 0 -1]]


In [17]:
# Vamos criar uma matriz coluna (vetor) a salvar na variável 'v0'.

In [18]:
v0 = np.array([[1], [0]])

In [19]:
# imprimindo a matriz salva na variável 'v0'

In [20]:
print(v0)

[[1]
 [0]]


In [21]:
# criando outra matriz coluna e a salvando na variável 'v1'

In [22]:
v1 = np.array([[0], [1]])

In [23]:
# imprimindo a matriz salva na variável 'v1'

In [24]:
print(v1)

[[0]
 [1]]


In [25]:
# Vamos criar outra matriz quadrada (2 linhas x 2 colunas) e a salvando na variável 'M'

In [26]:
M = np.array([[1,1], [1, -1]])

In [27]:
# imprimindo a matriz M

In [28]:
print(M)

[[ 1  1]
 [ 1 -1]]


In [29]:
# No Python, podemos dividir uma matriz por um número usando '/' e multiplicar usando '*',

# do mesmo modo que fazemos com números

In [30]:
print(2 * 2)

4


In [31]:
print(2 / 2)

1.0


In [32]:
print(M * 2)

[[ 2  2]
 [ 2 -2]]


In [33]:
print(M / 2)

[[ 0.5  0.5]
 [ 0.5 -0.5]]


In [34]:
# Como visto acima, dividir uma matriz por um número

# significa dividir todos os seus elementos dessa matriz por esse número.

# Multiplicar uma matriz por um número significa multiplicar todos os seus elementos por esse número.

In [35]:
# Um exemplo de multiplicação é a chamada operação 'hadamard',

# que significa dividir a matriz pela raiz quadrada de 2

In [36]:
# Vamos aplicar a operação 'hadamard' na matriz M, e salvar o resultado na matriz 'Had'

In [37]:
Had = (1/np.sqrt(2)) * M

In [38]:
# imprimindo a matriz salva na variável 'Had'

In [39]:
print(Had)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [40]:
# Para multiplicar 2 matrizes, o procedimento é mais complexo.

In [41]:
# No Python, usamos o símbolo '@'.

In [42]:
print(Sz@Sz)

[[1 0]
 [0 1]]


In [43]:
# Atenção, o asterisco '*' é usado para multiplicar um número por uma matriz somente.

In [44]:
print(2 * Sz)

[[ 2  0]
 [ 0 -2]]


In [45]:
# Não devemos usar o asterisco '*' para multiplicar matrizes.

In [46]:
# Se tentarmos, ocorre uma multiplicação diferente (aᵢⱼ x bᵢⱼ) da que queremos.

In [47]:
# O problema é que como o Python não retorna erro, mas um resultado errado,

# só vamos perceber o erro muitas vezes lá na frente do código.

In [48]:
# -----------------------------------------------------------------

In [49]:
# A função para transpor matrizes é a 'transpose()'

In [50]:
# Lembrando do vetor v0

In [51]:
print(v0)

[[1]
 [0]]


In [52]:
# Transpondo o vetor v0

In [53]:
print(np.transpose(v0))

[[1 0]]


In [54]:
# Outra particularidade da multiplicação de matrizes

# é que a ordem dos fatores altera o produto (não há a propriedade de comutatividade).

In [55]:
# Por exemplo, ao multiplicarmos um vetor linha por um vetor coluna,

In [56]:
# a ordem da multiplicação altera o resultado final.

In [57]:
# Por exemplo, vamos salvar o vetor zero 'horizontal' na variável v0_transposto.

In [58]:
v0_transposto = np.transpose(v0)

In [59]:
# Veja como a ordem importa. Multiplicando v0 com v0_transposto:

In [60]:
print(v0@v0_transposto)

[[1 0]
 [0 0]]


In [61]:
# Multiplicando na ordem inversa (veja que o resultado é diferente)

In [62]:
print(v0_transposto@v0)

[[1]]


In [63]:
# Regra:'vetor coluna' x 'vetor linha' = 'matriz'

In [64]:
# Regra: 'vetor linha' x 'vetor coluna' = 'número escalar'

In [65]:
# -----------------------------------------------------------

In [66]:
# Podemos criar um vetor que seja a combinação linear de outros vetores

In [67]:
# Por exemplo, criando um vetor Psi (combinação linear do vetor v0 e do vetor v1)

In [68]:
# Vamos definir Psi como (1/√2 * v0) + (1/√2 * v1)

In [69]:
Psi_na_base_v0_v1 = (1/np.sqrt(2) * v0) + (1/np.sqrt(2) * v1)

In [70]:
# imprimindo o vetor Psi

In [71]:
print(Psi_na_base_v0_v1)

[[0.70710678]
 [0.70710678]]


In [72]:
# Acima, escrevemos o vetor Psi nas bases v0 e v1

In [73]:
# Mas podemos escrevê-lo em quaisquer outras bases

In [74]:
# Por exemplo, vamos definir outro par de bases: va = [0, 2/√2], vb = [3√2, 0]

In [75]:
va = np.array([[0], [2/np.sqrt(2)]])

In [76]:
vb = np.array([[3/np.sqrt(2)], [0]])

In [77]:
# Podemos escrever o vetor Psi também como uma combinação linear de 'va' e 'vb'

In [78]:
# Psi = (1/2 * va) + (1/3 * vb)

In [79]:
Psi_na_base_a_b = (1/2 * va) + (1/3 * vb)

In [80]:
print(Psi_na_base_a_b)

[[0.70710678]
 [0.70710678]]


In [81]:
# Qualquer estado quântico representado por um vetor (Psi, no nosso exemplo) 

# pode ser escrito em qualquer base do seu espaço vetorial

# ([vo, v1] ou [va, vb], no nosso por exemplo).

In [82]:
# A base é só uma forma de escrever o vetor. Mas o vetor em si (o estado quântico) é o mesmo,
# independentemente se estiver escrito em uma base ou na outra.

In [83]:
# O que muda é o quanto de cada base precisamos somar para obter aquele vetor.

In [84]:
# Uma analogia, podemos escrever o número 10 usando as bases [n=2, m=4], assim:
# 10 = (1 * n) + (2 * m) = (1 * 2) + (2 * 4) = (2) + (8) = 10.

# Agora, usando as bases [n=5, m=5]:
# 10 = (1 * n) + (1 * m) = (1 * 5) + (1 * 5) = (5) + (5) = 10.

# O que mudou foi o quanto de cada base foi necessária, mas o resultado final (10) foi o mesmo.
# Semelhantemente, Psi pode ser escrito como 1/√2 de v1 e 1/√2 de v2, ou 1/2 de va e 1/3 vb.